schema_version = "1.0.0"

id = "hntools"
version = "0.0.1"
name = "HN Tools"
tagline = "Useful tools"
maintainer = "HaoNaN9279"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later",]
